### ISSUE TITLE
Mi Scale V2 not working

### ISSUE THREAD

**Issue by stefangries** [Bluetooth-Devices/xiaomi-ble#20]
**Describe the bug**
I don't know if the device is not supported or if it is a bug. Anyway, the scale does not appear in Home Assistant

**To Reproduce**
Step on the scale and watch as nothing happens in Home Assistant ;-)

**Additional context**
I recently switched from ble_monitor, it worked there.
I own the XMTZC05HM, which seems to be identical to XMTZC04HM.

**Comment by Jc2k** [comment]
So far HA has been creating an integration for each py file in this list: https://github.com/custom-components/ble_monitor/tree/master/custom_components/ble_monitor/ble_parser. This work has largely been done by volunteers that have devices for testing. As such there is not 100% coverage yet. Your device is covered by miscale.py, and this library covers xiaomi.py. No one has made an integration for miscale yet.
