### ISSUE TITLE
Add support for YLKG07YL/YLKG08YL dimmers

### ISSUE THREAD

**Issue by destman** [Bluetooth-Devices/xiaomi-ble#25]
This dimmers works with "Passive BLE monitor". But not with "Xiaomi BLE". It shows name but there is no object that will report states of dimmer. 
This is the only thing i miss to migrate from  Passive BLE monitor. Any chance parsing of events from these dimmers will be added ?

**Comment by Jc2k** [comment]
Yes it will be added in time, the parser was ported over from passive ble monitor in such a way as to preserve all the unsupported stuff. We are chipping away at it in our spare time, which is lacking at the moment.

**Comment by Ernst79** [comment]
Just a quick note. Adding these dimmers is somewhat more complicated, as it will need to send "device_events/triggers". So far, we have only added sensors and binary sensors.

**Comment by Ernst79** [comment]
PR is ready #67
