### ISSUE TITLE
Light/illuminance sensors

### ISSUE THREAD

**Issue by Ernst79** [Bluetooth-Devices/xiaomi-ble#4]
**Describe the bug**
in 0.2.0, you have changed the following

![image](https://user-images.githubusercontent.com/24375847/180617810-ab4fc81b-e0b1-4021-b1c1-aa31ed76e014.png)

This means you have removed the "light" output, which is used for some other Xiaomi devices. The "problem" is that some Xiaomi sensors use the illuminance sensor for a binary sensor (light/dark), with 100 being light and 0 being dark. 

In BLE monitor, I had a large table in constants.py in which I was able to tell which device has which sensor, so e.g. the MiFlora would not show a light sensor, as I had defined it to only use illuminance (lux) sensor. 

I think we should include this device specific output in the parser, I e.g. have already done that with the button and switch output, as Xiaomi uses the same "switch" data for different type of devices. 

I will try to reproduce which devices use "illuminance" sensors and which uses "light (dark/light)" binary sensors. 

**To Reproduce**

**Additional context**

**Comment by bdraco** [comment]
I am thinking about adding a update_predefined_binary_sensor call once my motion sensors I ordered show up and I have a test case

**Comment by Ernst79** [comment]
Great, I thing we will definitely need that for xiaomi-ble, as xiaomi has several switch , opening (open/closed), moisture (wet/dry), motion (motion/no motion) binary sensors, etc. Just check the list in const.py of ble monitor, there are about 10 

I made this note/issue to not forget to re-add this light sensor, as it was now removed from the code, making it hard remember to re-add it later, when we start with the binary sensors. I guess it is better to leave the old result dictionary output for this light sensor in the code, till we are adding the binary sensors. For now, we should only remove the illuminance sensor, as we use the `device.update_predefined_sensor` now). Will fix that. 

Note to myself.
Light binary sensor is used by
- MCCGQ02HL
- MJYD02YL
- RTCGQ02LM
- CGPR1

Illuminance lux sensor is used by
- HHCCJCY01
- GCLS002
- CGPR1

So CGPR1 uses both, the others use only one. 

Next step, I will look which device uses which data type for illuminance/light. 

Available data types
0x000F (motion, illuminance and light)
0x1007 (Illuminance & light)
0x1018 (light)

I remember that there is one devices that uses two data types for light or illuminance.

**Comment by Jc2k** [comment]
Ah if I had known that I would have left it in the unhandled dict, I thought it was some kind of convenience field that we wouldn't need now there was a proper entity. Yes, we should add it back to unhandled dict.

So far everything that was supported by the old code is still there (apart from this) and (apart from this) I'm only removing what can be handled by the new code. Did indeed do this exactly so we wouldn't forget what still needed porting.

Will get started on binary devices as soon as the framework is in place.

**Comment by Ernst79** [comment]
Created a PR to bring it back (and added the illuminance sensor for CGPR1), see #5

Xiaomi (and others) tend to misuse the light/illuminance. I fixed that by using the list in const.py to tell which devices uses what, but we don't have that anymore now. So we should bring this intelligence into the parser. When you start with the binary sensors, it becomes really tricky, especially at the buttons, remotes and switches. 

I will check which device needs what tomorrow for illuminance and light, to start with.

**Comment by Jc2k** [comment]
With binary stuff so they normally advertise an off value and then when triggered give an on value? How long do they show as on?

Or do they only send an "on" value when something (like motion) is detected, and if there is no broadcast there is no motion?

(If it's a stateless event we will need to fake the binary sensor transitioning from off to on and back to off, possibly with a timeout).

**Comment by Ernst79** [comment]
For light it is more a dark/light indicator, it is either light (100 or 256) or dark (0). I translated this to a binary light sensor in HA. But there is also and data type that combines it with motion. 

Motion is a more complicated one, as some sensors send “on” when motion detected and “ off” messages after a certain time. But others do only send “on”, they never send “off”. I therefore have added a configuration option with a motion timer, when motion is detected, motion timer = 1 is parsed and the countdown timer is restarted. After the set time, it is turned off. We will have to make something similar, I guess.

**Comment by Jc2k** [comment]
Probably a good one for @bdraco to have in mind when designing the update_predefined_binary_sensor API. Right now theres nothing to attach a timer to (we don't currently do any event loop stuff).

**Comment by Ernst79** [comment]
Ok, I made an overview of which sensor uses what data type. I distinguish between a illuminance sensor (= lux reading) and a light sensor (= binary dark/light sensor)

**HHCCJCY01**
- illuminance sensor `0x1007`

**GCLS002**
- illuminance sensor `0x1007`

**CGPR1**
- illuminance sensor `0x000F` In BLE monitor, CGPR1 also has a binary light sensor based on lux < 100 = dark, lux >= 100 = light. Not sure why we did that, but I guess this isn't really needed. Each measurement is movement

**MJYD02YL**
- light sensor `0x000F` 1 = dark, 100 = light, each message means movement
- light sensor `0x1007` 100 = light, else dark (I think dark is 1 or 0)

**RTCGQ02LM**
- light sensor `0x000F` 0 = dark, 256 = light, each message means movement
- light sensor `0x1018` 0 = dark, 1 = light

**MCCGQ02HL**
- light sensor, either `0x1007` or `0x1018` not sure which one

As you can see, the data types are often used by one device as a lux sensor, and for other devices as a light sensor.
And one device can use two different messages for light/lux, one is with movement, the other just light/lux

So, if we translate the above to the data types in the xiaomi-ble parser, we get

**`0x000F`**
- illuminance sensor (and motion sensor) for CGPR1
- light sensor (and motion sensor) for MJYD02YL (1 = dark, 100 = light)
- light sensor (and motion sensor) for RTCGQ02LM (0 = dark, 256 = light)

**`0x1007`**
- illuminance sensor for HHCCJCY01
- illuminance sensor for GCLS002
- light sensor for MJYD02YL (100 = light, else dark)
- light sensor for MCCGQ02HL (100 = light, else dark) (could also use `0x1018`)

`0x1018`
- light sensor for RTCGQ02LM (0 = dark, 1 = light)
- light sensor for MCCGQ02HL  (0 = dark, 1 = light) (could also use `0x1007`)

I'll update the parser in a minute, such that each device only give the output it should create a sensor for.

**Comment by Ernst79** [comment]
I guess we can close this issue.
