### ISSUE TITLE
JTYJGD03MI is defined as a thermometer but is a smoke detector.

### ISSUE THREAD

**Issue by ahmetem** [Bluetooth-Devices/xiaomi-ble#45]
JTYJGD03MI is defined as a thermometer but is a smoke detector.
[product link](https://tr.aliexpress.com/item/1000008294002.html?spm=a2g0o.productlist.main.3.70dd1f74uTkhJ9&algo_pvid=575ab0cb-95e1-47bd-94c3-e0ce4eb0e14d&aem_p4p_detail=202305281156057972388732824820011461146&algo_exp_id=575ab0cb-95e1-47bd-94c3-e0ce4eb0e14d-1&pdp_npi=3%40dis%21TRY%21604.0%21591.93%21%21%21%21%21%402100b78b16853001656183283d07b2%2112000022064570758%21sea%21TR%21176954440&curPageLogUid=L21T4uUZ1dHY&p4p_pvid=202305281156057972388732824820011461146_2)
 0x0997: DeviceEntry(
        name="Thermometer",
        model="JTYJGD03MI"

![JTYJGD03MI](https://github.com/Bluetooth-Devices/xiaomi-ble/assets/26777241/73f45f9a-6401-4958-ad0d-86ae02e4640f)

**Comment by Ernst79** [comment]
Fixed in 17.2
