### ISSUE TITLE
Support of YLYK01YL remote

### ISSUE THREAD

**Issue by Styx85** [Bluetooth-Devices/xiaomi-ble#57]
Will the YLYK01YL remote be supported anytime soon here as it is functional in BLE Monitor? Or are there still some major problems in the way?
I opt in for testing if anything can be done.

**Comment by Ernst79** [comment]
PR is ready to implement this, see #65

**Comment by Styx85** [comment]
This is very good news. Is there any help in testing this I can do?
And of course thank you for doing the work.

**Comment by Ernst79** [comment]
Not yet. I will merge this change in xiaomi-ble tomorrow, after that, I need to make some small changes to the integration in Home Assistant. But the big work has already been done. (adding the `event entity` in Home Assistant for the xiaomi-ble integration, which got merged a few hours ago). The event entity thing was something we needed first, as the remotes don't send "sensor states", but they send "events" (in HA terms). 

After the PR for HA is ready, you can test it. I'll let you know. I expect somewhere this week.
