### ISSUE TITLE
Would pvvx broadcast support be welcome?

### ISSUE THREAD

**Issue by agittins** [Bluetooth-Devices/xiaomi-ble#58]
I have a pile of Xiaomi LYWSD03MMC thermometers scattered about the house. Almost all are currently configured with the "custom" broadcast format from [PVVX's firmware](https://github.com/pvvx/ATC_MiThermometer#bluetooth-advertising-formats). They're running an older version so don't have the BTHome format available. I currently use an esp32 running esphome to receive and decode the pvvx broadcasts [using the `pvvx_mithermometer` component](https://esphome.io/components/sensor/xiaomi_ble#lywsd03mmc).

Eventually I'll reflash them and configure them for BTHome so they can leverage the network of ble_proxy's I have, and I feel that's the "proper" solution, but I am weighing up between doing the cumbersome flash and reconfigure process on them all now, versus adding native HA support for the protocol instead and delay reflashing them until they individually need their batteries replaced.

Is adding the protocol here, and adding the uuid to the manifest for the HA component the way to do that? And secondly, is it something there is interest in implementing or accepting a PR for?

I'd understand if there isn't given it's sort of an "interim" protocol between the native xiaomi and bthome protocols, but wanted to get an idea for where it's worthwhile putting in effort. I imagine I'm not alone in having deployed units with this firmware, but there probably aren't a *lot* of us, and we all probably anticipate having to bite the bullet and reflash them at some point...

(below is the format description from the above-linked pvvx ATC_MiThermometer repo)
![image](https://github.com/Bluetooth-Devices/xiaomi-ble/assets/752405/034316ed-e251-4de5-9001-290a23dde5b5)

**Comment by bdraco** [comment]
A new protocol would mean a new library and a new integration.  It would not be something we would want to add to this library.

**Comment by Jc2k** [comment]
I'd also prefer not to support a third protocol for these devices full stop. Just because code that doesn't exist doesn't have to be maintained.

**Comment by agittins** [comment]
No worries, that's fair enough given there's a clear path to a supported solution (ie, reflashing and using BTHome).

Thanks for the prompt responses.
