### ISSUE TITLE
Cheap Tuya temperature sensor support - offer to contribute

### ISSUE THREAD

**Issue by zalatnaicsongor** [Bluetooth-Devices/xiaomi-ble#84]
There are cheap Tuya temperature sensors like https://www.aliexpress.com/item/1005006010340464.html (can be had for $2 more often than not) - they have a well defined protocol, and if the deviceId/localKey is known, the advertisements can be decoded.

If there is willingness to include such feature in this library (given that the Tuya HHCCwhatever is already supported), I'd like to implement it and contribute it to this package & add the relevant code to the home assistant addon.

**Comment by Ernst79** [comment]
I think it would be better to create a copy of this package and release it as tuya-ble or something similar. This packages focusses on the devices that are sold as xiaomi brand and that mostly advertise with the xiaomi UUID (95FE). Some HHCC plant sensors were added, as these are sold under different names, including Xiaomi. There are also brands that use the MiBeacon format, which are included for that reason. But I think Tuya should get its own package, like we did for Qingping, Govee, etc. A copy of an existing package would be a good start, I guess. We can create create a repo under Bluetooth-Devices if needed.

**Comment by zalatnaicsongor** [comment]
Oh good, I didn't notice there were other libraries 🥲
I'll create a new repo under my user, then if the quality's good enough, it can be transferred to Bluetooth-Devices.
I guess the same goes for the home assistant component, correct?

**Comment by Ernst79** [comment]
Yep, each BLE brand has its own integration, but the integrations are mostly similar set up.
